### ISSUE TITLE
Missing README.md on pip

### ISSUE THREAD

**Issue by suedwestlich** [florianl/panonoctl#1]
# pip install panonoctl

Collecting panonoctl
  Using cached panonoctl-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-axTJcP/panonoctl/setup.py", line 22, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by suedwestlich** [comment]
Also missing a dependency

https://pypi.python.org/simple/struct/

Installed /usr/local/lib/python2.7/dist-packages/panonoctl-0.3-py2.7.egg
Processing dependencies for panonoctl==0.3
Searching for struct
Reading https://pypi.python.org/simple/struct/
Couldn't find index page for 'struct' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for struct
error: Could not find suitable distribution for Requirement.parse('struct')

seems to not exist anymore

**Comment by florianl** [comment]
Hi @suedwestlich !
Thanks for mention the issues.
In https://github.com/florianl/panonoctl/commit/480a3c64abdb97979d007ec230cdbd221a80011d I removed _struct_ from the requirements.

Regarding the issue with README.md:
I can not find the problem so far ... so I will have to take a further look at it.

Cheers,
 Florian

**Comment by florianl** [comment]
Hi @suedwestlich !
Thanks again for reporting this issue.
The file MANIFEST.in was missing and added by https://github.com/florianl/panonoctl/commit/547fac9e141c981c5f66fdea208cd9d60f0e598a .

If you find further bugs, please let me know!

Cheers,
 Florian
