### ISSUE TITLE
func delete_upf() in panono.py

### ISSUE THREAD

**Issue by suedwestlich** [florianl/panonoctl#2]
Hi,

two issues with function delete_upf, because:
1. there is a typo at:
   ... "method":"delte_upf" ...
2. "parameters" must be named "params" (in delete_upf())

With these changes, we got func delete_upf to work.

Regards,
Simon

**Comment by florianl** [comment]
Hi @suedwestlich 

Thanks again for your feedback!
I fixed the issues in https://github.com/florianl/panonoctl/commit/f808274ca2101f25a3a889f44cd3f6ad949d8c22 and https://github.com/florianl/panonoctl/commit/76d8c5055990b2bcfd2cd35a311173ac4f36423a and pushed a new minor version.

Regards,
 Florian
