### ISSUE TITLE
Package 'socket' must not be downloaded from pypi

### ISSUE THREAD

**Issue by neuhargj** [florianl/panonoctl#3]
ran into:

"RuntimeError: Package 'socket' must not be downloaded from pypi"

removed socket from installs_required in setup.py, then re-packaged and installed locally with pip install

**Comment by florianl** [comment]
Hey!
Thanks for the notice.
I've updated the package: https://github.com/florianl/panonoctl/commit/b52e007bdf05e233b1d4a302838dfb440e67f9b8

Best regards,
 Florian
