### ISSUE TITLE
Any walkthrough, examples for connecting to Panono?

### ISSUE THREAD

**Issue by neuhargj** [florianl/panonoctl#4]
Cannot get connected. Do you have any walkthroughs or examples on getting started? Thanks.

**Comment by florianl** [comment]
Hey!
In https://github.com/florianl/panonoctl#documentation all steps are written down.

``` python
>>> from panonoctl import panono
>>> cam = panono()
>>> cam.connect()
>>> cam.capture()
>>> cam.disconnect()
```

Best regards,
 Florian

**Comment by neuhargj** [comment]
Hi @florianl,

Sorry for the confusion, I meant more along the lines of how do I connect. I am having trouble identifying the IP of the Panono, the port to talk on, and which path to connect to; also, do I hard code these values into panono.py?

Thanks

**Comment by florianl** [comment]
Hi @neuhargj ,
the Panono periodically sends Simple Service Discovery Protocol (SSDP) messages.
These messages are used by the provided library, to extract the necessary information to communicate with the camera. Thus, you do not need to enter such information.
You simply need to be connected to the WiFi from the Panono.

**Comment by florianl** [comment]
If there are further questions, feel free to ask @neuhargj .
Otherwise, I will close this issue.

**Comment by florianl** [comment]
Hi @neuhargj 
I pushed a new version. Please let me know, if you've got still problems.

In my last walkthrough I missed to do the auth().

``` python
>>> from panonoctl import panono
>>> cam = panono()
>>> cam.connect()
>>> cam.auth()
>>> cam.capture()
>>> cam.disconnect()
```

Kind regards,
 Florian

**Comment by florianl** [comment]
I close this issue. If there are further problems, feel free to open an issue.
Thanks for your feedback!

**Comment by neuhargj** [comment]
hi @florianl, sorry for the late response, ive had a few other projects going. i am still unable to connect, on cam.connect() i get "timed out" and "false", i was trying to connect through a virtual machine and i didnt know if the virtualization was causing an issue, so i was trying to run on a raspberry pi instead.

**Comment by florianl** [comment]
Hej @neuhargj 
if you are connected to the WLAN of the panon, run as root
`tcpdump -vv -A -s 0 -i $YOUR_WLAN_INTERFACE udp port 1900 and host 239.255.255.250`
do you get SSDP messages? If there are no messages, then it is a network problem.
Otherwise, if there is an output, please paste it here.

Kind regards,
   Florian

**Comment by neuhargj** [comment]
@florianl,

i was able to get past the timed out, false problem, but hten i ran into an issue with the websocket module not having a create_connection method; i researched this previously and tried to manually switch over to a different module, but this did not work.

<img width="735" alt="screen shot 2016-11-15 at 4 39 59 pm" src="https://cloud.githubusercontent.com/assets/8126671/20325409/86e830de-ab52-11e6-905b-26d1b799fa57.png">

**Comment by florianl** [comment]
Did you install panonoctl from github.com or using pip?

**Comment by neuhargj** [comment]
@florianl, ive tried from both the github project and pip from my macbook pro, an ubuntu vm, and a raspberry pi, no luck

**Comment by florianl** [comment]
hej @neuhargj 
the missing attribute `create_connection` looks like a missing dependency.
Is `websocket` installed as required in https://github.com/florianl/panonoctl/blob/master/setup.py#L33 ?
For an easy update, you can use: `pip install -U panonoctl`

Do you get SSDP messages? And how do they look like?

**Comment by neuhargj** [comment]
@florianl, do you have a link to the websocket module? all i can find is websocket-connection module that has a create_connection function

https://pypi.python.org/pypi/websocket-client/

i do not get any ssdp messages

**Comment by florianl** [comment]
hej @neuhargj 
If there are no ssdp messages, you are not connected to the WLAN of the panono properly.
Without these ssdp messages, this python module will not work.

**Comment by neuhargj** [comment]
@florianl,

i am getting the ssdp packets, but still getting the same error, please see below:

<img width="735" alt="screen shot 2016-11-15 at 4 39 59 pm" src="https://cloud.githubusercontent.com/assets/8126671/20536836/aea3a188-b0b8-11e6-8f74-8e4d2b359ebf.png">

<img width="457" alt="screen shot 2016-11-22 at 1 35 17 pm" src="https://cloud.githubusercontent.com/assets/8126671/20536813/98e7912e-b0b8-11e6-885f-0edae9fe9bb3.png">

**Comment by florianl** [comment]
hej @neuhargj 
I fixed the issue with the requirement by using [websocket-client](https://pypi.python.org/pypi/websocket-client) in 'setup.py'. I'm sorry for the circumstances.
For an easy update, you can use: `pip install -U panonoctl`

Looking forward for your feedback

**Comment by neuhargj** [comment]
@florianl,
thanks for your updates, everything is working fine now. you've built a great tool

**Comment by florianl** [comment]
thanks @neuhargj 
now - I will close this issue.
